import type { CSSProperties } from 'react';

export type BlobTheme = CSSProperties & Record<`--${string}`, string>;

export const defaultBlobTheme: BlobTheme = {
    '--jelly-body-top': '#ecb8ff',
    '--jelly-body-mid': '#c57af3',
    '--jelly-body-deep': '#a662e8',
    '--jelly-body-rim': '#d292fb',
    '--jelly-outline': '#8d52de',
    '--jelly-outline-light': '#b66af0',
    '--jelly-arm-light': '#e1a8ff',
    '--jelly-arm-mid': '#bc78ed',
    '--jelly-arm-deep': '#9c5de2',
    '--jelly-cheek-light': '#ffc5e2',
    '--jelly-cheek': '#f68fc8',
    '--jelly-cheek-deep': '#e87cb9',
    '--jelly-eye-light': '#37204b',
    '--jelly-eye': '#170d25',
    '--jelly-eye-deep': '#0d0715',
    '--jelly-belly-glow': '#ffb2dc',
    '--jelly-eye-sparkle': '#b471e6',
    '--jelly-shadow': '#8d52de',
    '--jelly-shadow-light': '#b66af0',
};

export const onTimeBlobTheme: BlobTheme = {
    '--jelly-body-top': '#a7f3d0',
    '--jelly-body-mid': '#34d399',
    '--jelly-body-deep': '#10b981',
    '--jelly-body-rim': '#6ee7b7',
    '--jelly-outline': '#059669',
    '--jelly-outline-light': '#34d399',
    '--jelly-arm-light': '#a7f3d0',
    '--jelly-arm-mid': '#34d399',
    '--jelly-arm-deep': '#10b981',
    '--jelly-cheek-light': '#bbf7d0',
    '--jelly-cheek': '#6ee7b7',
    '--jelly-cheek-deep': '#34d399',
    '--jelly-eye-light': '#064e3b',
    '--jelly-eye': '#022c22',
    '--jelly-eye-deep': '#011a14',
    '--jelly-belly-glow': '#a7f3d0',
    '--jelly-eye-sparkle': '#34d399',
    '--jelly-shadow': '#059669',
    '--jelly-shadow-light': '#34d399',
};

export const lateBlobTheme: BlobTheme = {
    '--jelly-body-top': '#fecaca',
    '--jelly-body-mid': '#ef4444',
    '--jelly-body-deep': '#dc2626',
    '--jelly-body-rim': '#f87171',
    '--jelly-outline': '#b91c1c',
    '--jelly-outline-light': '#ef4444',
    '--jelly-arm-light': '#fecaca',
    '--jelly-arm-mid': '#ef4444',
    '--jelly-arm-deep': '#dc2626',
    '--jelly-cheek-light': '#fecaca',
    '--jelly-cheek': '#f87171',
    '--jelly-cheek-deep': '#ef4444',
    '--jelly-eye-light': '#7f1d1d',
    '--jelly-eye': '#450a0a',
    '--jelly-eye-deep': '#2c0505',
    '--jelly-belly-glow': '#fecaca',
    '--jelly-eye-sparkle': '#f87171',
    '--jelly-shadow': '#b91c1c',
    '--jelly-shadow-light': '#ef4444',
};
